name: CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Client Folder
    - run: cd client/
    
    - name: Yarn Install
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
    
    - name: Yarn Build
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build # will run `yarn build` command
        
    - name: Yarn Deploy
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: deploy
