name: CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Build
      working-directory: ./client
      env:
        CI: ''
      run: | 
        npm install
        npm run build
        
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./client/build # The folder the action should deploy.
