name: CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        
    - name: Build and Deploy
      working-directory: ./client
      run: | 
        npm install
        npm run build
        npm run deploy
