name: CI/CD

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Client Folder
      run: cd client/

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
      
    - name: Deploy
      run: npm run deploy
